name: Go

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Generate
      run: make generate

    - name: Lint
      run: make lint

    - name: Unit test
      run: make unit-test

    - name: Archive unit test code coverage
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: coverage.out
        path: coverage.out

    - name: Integration test
      run: make integration-test
